name: Empty the Container & Upload the new files 

on:
  workflow_dispatch:

env:
  container: 'https://<bucket name>.blob.core.windows.net/<Folder name>'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Install azcopy
        uses: kheiakiyama/install-azcopy-action@v1.0.3

      # Delete all files in the container
      - name: Empty the container
        run: azcopy remove '${{ env.container }}?${{ secrets.SAS_TOKEN }}' --recursive

      # Copy the contents of the current directory
      - name: Copy new files
        run: azcopy copy '<Folder name>/*' '${{ env.container }}?${{ secrets.SAS_TOKEN }}' --recursive --from-to=LocalBlob
